version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecommerce
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_backup:/backup

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: mysql # Menunjukkan nama service MySQL
      PMA_PORT: 3306 # Port MySQL
      PMA_USER: admin # Username untuk login ke MySQL
      PMA_PASSWORD: admin # Password root MySQL
    ports:
      - "8081:80" # Mengakses phpMyAdmin di http://localhost:8081

volumes:
  mysql_data:
    driver: local
  mysql_backup:
    driver: local
